CALL_OF_DUTY_API_EMAIL = ''
CALL_OF_DUTY_API_PASSWORD = ''

CALL_OF_DUTY_SEARCH_CACHE_KEY = '{}_{}_search'
CALL_OF_DUTY_PROFILE_CACHE_KEY = '{}_profile'
CALL_OF_DUTY_TITLE_PROFILE_CACHE_KEY = '{}_{}_{}_profile'
CALL_OF_DUTY_TITLE_MODE_STATS_KEY = '{}_{}_stats'
CALL_OF_DUTY_TITLE_LEADERBOARD_CACHE_KEY = '{}_{}_{}_leaderboard'
CALL_OF_DUTY_TITLE_UNIFIED_LEADERBOARD_CACHE_KEY = '{}_{}_leaderboard'

CALL_OF_DUTY_MODULE_LABELS = {
	"record_longest_win_streak": "Longest Recorded Win Streak",
	"record_xp_in_a_match": "Record XP earned in a Match",
	"accuracy": "Accuracy",
	"losses": "Total Losses",
	"total_games_played": "Total games played",
	"win_loss_ratio": "Win Loss Ratio",
	"total_shots": "Total shots fired",
	"best_score_xp": "Best Score XP",
	"games_played": "Games Played",
	"deaths": "Total deaths",
	"wins": "Total wins",
	"score": "Total score",
	"kd_ratio": "KD Ratio",
	"best_assists": "Most Assists in a mach",
	"best_score": 'Highest score',
	"record_deaths_in_a_match": 'Highest deaths',
	'score_per_game': 'Average score per game',
	'record_kills_in_a_match': 'Highest kills',
	'suicides': 'Total suicides',
	'current_win_streak': 'Current winstreak',
	'kills': 'Total kills',
	'time_played_total': 'Total time played',
	'headshots': 'Total headshots',
	'assists': 'Total assists',
	'misses': 'Total shots missed',
	'misses': 'Total misses',
	'score_per_minute': 'Average SPM',
	'hits': 'Total hits',
	'best_kill_streak': 'Highest killstreak',
	'time_played': 'Total time played',
	'defuses': 'Total defuses',
	'plants': 'Total plants',
	'defends': 'Total defends',
	'avg_life_time': 'Average time alive',
	'objective_teams_wiped': 'Total team wipes',
	'wall_bangs': 'Total wall bangs',
	'kills_per_game': 'Average kills per game',
	'distance_travelled': 'Total distance travelled',
	'objective_munitions_box_teammate_used': 'Total munition boxes used',
	'gulag_deaths': 'Total deaths in gulag',
	'time_played': 'Total time played',
	'headshot_percentage': 'Average headshot percentage',
	'matches_played': 'Total matches played',
	'gulag_kills': 'Total gulag kills',
	'damage_done': 'Total damage done',
	'damage_taken': 'Total damage taken',
	'objective_br_mission_pickup_tablet': 'Total missions',
	'infected': 'Total infected',
	'time': 'Time played',
	'match_id': 'Match API ID',
	'utc_start_seconds': 'Match started at',
	'utc_end_seconds': 'Match ended at',
	'team_survival_time': 'Team survival time',
	'player_count': 'Total player count',
	'rank': 'Placement',
	'mode': 'Game Mode',
	'uses': 'Total uses',
	'awarded_count': 'Total times awarded'
}